# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

env:
    SLN_PATH: './src/TestProject1.sln'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup PostgreSQL With Init Scripts
      uses: m4nu56/postgresql-action@1.0
      with:
          postgresql version: 13
          postgresql db: postgres
          postgresql user: postgres
          postgresql password: NoPassword1
          postgresql init scripts: ./seeds/
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ${{env.SLN_PATH}} 
    - name: Build
      run: dotnet build --no-restore ${{env.SLN_PATH}} 
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{env.SLN_PATH}} 
